/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Basketball' : IDL.Null,
  'Tennis' : IDL.Null,
  'Football' : IDL.Null,
  'Cricket' : IDL.Null,
  'Badminton' : IDL.Null,
});
export const AddProductRequest = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'brand' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const AddReviewRequest = IDL.Record({
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Review = IDL.Record({
  'id' : ReviewId,
  'userId' : UserId,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'timestamp' : Timestamp,
  'rating' : IDL.Nat,
});
export const AddToCartRequest = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrdersByStatus = IDL.Record({
  'shipped' : IDL.Nat,
  'cancelled' : IDL.Nat,
  'placed' : IDL.Nat,
  'delivered' : IDL.Nat,
  'processing' : IDL.Nat,
});
export const TopProduct = IDL.Record({
  'revenue' : IDL.Nat,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'totalSold' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'ordersByStatus' : OrdersByStatus,
  'totalOrders' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'topProducts' : IDL.Vec(TopProduct),
  'totalRevenue' : IDL.Nat,
  'monthlyRevenue' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Placed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
});
export const Address = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
  'NetBanking' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'couponCode' : IDL.Opt(IDL.Text),
  'total' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'discountAmount' : IDL.Nat,
  'timestamp' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Cart = IDL.Record({
  'total' : IDL.Nat,
  'userId' : UserId,
  'items' : IDL.Vec(CartItem),
});
export const Wishlist = IDL.Record({
  'productIds' : IDL.Vec(ProductId),
  'userId' : UserId,
});
export const MessageId = IDL.Nat;
export const ContactMessage = IDL.Record({
  'id' : MessageId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'addresses' : IDL.Vec(IDL.Text),
});
export const PlaceOrderRequest = IDL.Record({
  'deliveryAddress' : Address,
  'couponCode' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'items' : IDL.Vec(OrderItem),
});
export const SubmitContactRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const UpdateCartItemRequest = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const UpdateProductRequest = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([AddProductRequest], [Product], []),
  'addReview' : IDL.Func([AddReviewRequest], [Review], []),
  'addToCart' : IDL.Func([AddToCartRequest], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'filterProducts' : IDL.Func(
      [
        IDL.Opt(Category),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getWishlist' : IDL.Func([], [Wishlist], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listProducts' : IDL.Func([IDL.Opt(Category)], [IDL.Vec(Product)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [Order], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'submitContactMessage' : IDL.Func(
      [SubmitContactRequest],
      [ContactMessage],
      [],
    ),
  'toggleWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
  'updateCartItem' : IDL.Func([UpdateCartItemRequest], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'updateProduct' : IDL.Func([UpdateProductRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Basketball' : IDL.Null,
    'Tennis' : IDL.Null,
    'Football' : IDL.Null,
    'Cricket' : IDL.Null,
    'Badminton' : IDL.Null,
  });
  const AddProductRequest = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'brand' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const AddReviewRequest = IDL.Record({
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Review = IDL.Record({
    'id' : ReviewId,
    'userId' : UserId,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'timestamp' : Timestamp,
    'rating' : IDL.Nat,
  });
  const AddToCartRequest = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrdersByStatus = IDL.Record({
    'shipped' : IDL.Nat,
    'cancelled' : IDL.Nat,
    'placed' : IDL.Nat,
    'delivered' : IDL.Nat,
    'processing' : IDL.Nat,
  });
  const TopProduct = IDL.Record({
    'revenue' : IDL.Nat,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'totalSold' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'ordersByStatus' : OrdersByStatus,
    'totalOrders' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'topProducts' : IDL.Vec(TopProduct),
    'totalRevenue' : IDL.Nat,
    'monthlyRevenue' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Placed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
  });
  const Address = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
    'NetBanking' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : Address,
    'couponCode' : IDL.Opt(IDL.Text),
    'total' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'userId' : UserId,
    'discountAmount' : IDL.Nat,
    'timestamp' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Cart = IDL.Record({
    'total' : IDL.Nat,
    'userId' : UserId,
    'items' : IDL.Vec(CartItem),
  });
  const Wishlist = IDL.Record({
    'productIds' : IDL.Vec(ProductId),
    'userId' : UserId,
  });
  const MessageId = IDL.Nat;
  const ContactMessage = IDL.Record({
    'id' : MessageId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'addresses' : IDL.Vec(IDL.Text),
  });
  const PlaceOrderRequest = IDL.Record({
    'deliveryAddress' : Address,
    'couponCode' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'items' : IDL.Vec(OrderItem),
  });
  const SubmitContactRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const UpdateCartItemRequest = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const UpdateProductRequest = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([AddProductRequest], [Product], []),
    'addReview' : IDL.Func([AddReviewRequest], [Review], []),
    'addToCart' : IDL.Func([AddToCartRequest], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'filterProducts' : IDL.Func(
        [
          IDL.Opt(Category),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getWishlist' : IDL.Func([], [Wishlist], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(Category)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [Order], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'submitContactMessage' : IDL.Func(
        [SubmitContactRequest],
        [ContactMessage],
        [],
      ),
    'toggleWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
    'updateCartItem' : IDL.Func([UpdateCartItemRequest], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'updateProduct' : IDL.Func([UpdateProductRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };