/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddProductRequest {
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'brand' : string,
  'price' : bigint,
}
export interface AddReviewRequest {
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export interface AddToCartRequest {
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface Address {
  'street' : string,
  'city' : string,
  'fullName' : string,
  'state' : string,
  'phone' : string,
  'pincode' : string,
}
export interface AdminStats {
  'totalProducts' : bigint,
  'ordersByStatus' : OrdersByStatus,
  'totalOrders' : bigint,
  'totalUsers' : bigint,
  'topProducts' : Array<TopProduct>,
  'totalRevenue' : bigint,
  'monthlyRevenue' : bigint,
}
export interface Cart {
  'total' : bigint,
  'userId' : UserId,
  'items' : Array<CartItem>,
}
export interface CartItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export type Category = { 'Basketball' : null } |
  { 'Tennis' : null } |
  { 'Football' : null } |
  { 'Cricket' : null } |
  { 'Badminton' : null };
export interface ContactMessage {
  'id' : MessageId,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export type MessageId = bigint;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'couponCode' : [] | [string],
  'total' : bigint,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'discountAmount' : bigint,
  'timestamp' : Timestamp,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Placed' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null };
export interface OrdersByStatus {
  'shipped' : bigint,
  'cancelled' : bigint,
  'placed' : bigint,
  'delivered' : bigint,
  'processing' : bigint,
}
export type PaymentMethod = { 'UPI' : null } |
  { 'Card' : null } |
  { 'NetBanking' : null };
export interface PlaceOrderRequest {
  'deliveryAddress' : Address,
  'couponCode' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'items' : Array<OrderItem>,
}
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'brand' : string,
  'rating' : bigint,
  'price' : bigint,
  'reviewCount' : bigint,
}
export type ProductId = bigint;
export interface Review {
  'id' : ReviewId,
  'userId' : UserId,
  'productId' : ProductId,
  'comment' : string,
  'timestamp' : Timestamp,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface SubmitContactRequest {
  'name' : string,
  'email' : string,
  'message' : string,
}
export type Timestamp = bigint;
export interface TopProduct {
  'revenue' : bigint,
  'productId' : ProductId,
  'productName' : string,
  'totalSold' : bigint,
}
export interface UpdateCartItemRequest {
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface UpdateProductRequest {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'brand' : string,
  'price' : bigint,
}
export interface User {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'addresses' : Array<string>,
}
export type UserId = Principal;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wishlist { 'productIds' : Array<ProductId>, 'userId' : UserId }
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[AddProductRequest], Product>,
  'addReview' : ActorMethod<[AddReviewRequest], Review>,
  'addToCart' : ActorMethod<[AddToCartRequest], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'filterProducts' : ActorMethod<
    [[] | [Category], [] | [string], [] | [bigint], [] | [bigint]],
    Array<Product>
  >,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Wishlist>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'listProducts' : ActorMethod<[[] | [Category]], Array<Product>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], Order>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'submitContactMessage' : ActorMethod<[SubmitContactRequest], ContactMessage>,
  'toggleWishlist' : ActorMethod<[ProductId], boolean>,
  'updateCartItem' : ActorMethod<[UpdateCartItemRequest], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<[UpdateProductRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];