/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlaceOrderRequest {
    deliveryAddress: Address;
    couponCode?: string;
    paymentMethod: PaymentMethod;
    items: Array<OrderItem>;
}
export interface Address {
    street: string;
    city: string;
    fullName: string;
    state: string;
    phone: string;
    pincode: string;
}
export type Timestamp = bigint;
export interface Product {
    id: ProductId;
    name: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: Category;
    brand: string;
    rating: bigint;
    price: bigint;
    reviewCount: bigint;
}
export interface OrderItem {
    productId: ProductId;
    productName: string;
    quantity: bigint;
    price: bigint;
}
export interface AddReviewRequest {
    productId: ProductId;
    comment: string;
    rating: bigint;
}
export interface TopProduct {
    revenue: bigint;
    productId: ProductId;
    productName: string;
    totalSold: bigint;
}
export interface Wishlist {
    productIds: Array<ProductId>;
    userId: UserId;
}
export interface ContactMessage {
    id: MessageId;
    name: string;
    email: string;
    message: string;
    timestamp: Timestamp;
}
export interface AddProductRequest {
    name: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: Category;
    brand: string;
    price: bigint;
}
export interface Cart {
    total: bigint;
    userId: UserId;
    items: Array<CartItem>;
}
export type ReviewId = bigint;
export interface UpdateProductRequest {
    id: ProductId;
    name: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: Category;
    brand: string;
    price: bigint;
}
export interface Review {
    id: ReviewId;
    userId: UserId;
    productId: ProductId;
    comment: string;
    timestamp: Timestamp;
    rating: bigint;
}
export interface User {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
    addresses: Array<string>;
}
export interface UpdateCartItemRequest {
    productId: ProductId;
    quantity: bigint;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: Address;
    couponCode?: string;
    total: bigint;
    paymentMethod: PaymentMethod;
    userId: UserId;
    discountAmount: bigint;
    timestamp: Timestamp;
    items: Array<OrderItem>;
}
export type UserId = Principal;
export interface AdminStats {
    totalProducts: bigint;
    ordersByStatus: OrdersByStatus;
    totalOrders: bigint;
    totalUsers: bigint;
    topProducts: Array<TopProduct>;
    totalRevenue: bigint;
    monthlyRevenue: bigint;
}
export type MessageId = bigint;
export interface AddToCartRequest {
    productId: ProductId;
    quantity: bigint;
}
export interface OrdersByStatus {
    shipped: bigint;
    cancelled: bigint;
    placed: bigint;
    delivered: bigint;
    processing: bigint;
}
export type ProductId = bigint;
export interface CartItem {
    productId: ProductId;
    quantity: bigint;
    price: bigint;
}
export interface SubmitContactRequest {
    name: string;
    email: string;
    message: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export type OrderId = bigint;
export enum Category {
    Basketball = "Basketball",
    Tennis = "Tennis",
    Football = "Football",
    Cricket = "Cricket",
    Badminton = "Badminton"
}
export enum OrderStatus {
    Delivered = "Delivered",
    Placed = "Placed",
    Cancelled = "Cancelled",
    Processing = "Processing",
    Shipped = "Shipped"
}
export enum PaymentMethod {
    UPI = "UPI",
    Card = "Card",
    NetBanking = "NetBanking"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addProduct(req: AddProductRequest): Promise<Product>;
    addReview(req: AddReviewRequest): Promise<Review>;
    addToCart(req: AddToCartRequest): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    deleteProduct(id: ProductId): Promise<boolean>;
    filterProducts(category: Category | null, brand: string | null, minPrice: bigint | null, maxPrice: bigint | null): Promise<Array<Product>>;
    getAdminStats(): Promise<AdminStats>;
    getAllOrders(): Promise<Array<Order>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Cart>;
    getMyOrders(): Promise<Array<Order>>;
    getOrder(orderId: OrderId): Promise<Order | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    getProductReviews(productId: ProductId): Promise<Array<Review>>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    getWishlist(): Promise<Wishlist>;
    isCallerAdmin(): Promise<boolean>;
    listContactMessages(): Promise<Array<ContactMessage>>;
    listProducts(category: Category | null): Promise<Array<Product>>;
    listUsers(): Promise<Array<User>>;
    placeOrder(req: PlaceOrderRequest): Promise<Order>;
    removeFromCart(productId: ProductId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProducts(term: string): Promise<Array<Product>>;
    submitContactMessage(req: SubmitContactRequest): Promise<ContactMessage>;
    toggleWishlist(productId: ProductId): Promise<boolean>;
    updateCartItem(req: UpdateCartItemRequest): Promise<void>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<boolean>;
    updateProduct(req: UpdateProductRequest): Promise<boolean>;
}
import type { AddProductRequest as _AddProductRequest, Address as _Address, Category as _Category, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PlaceOrderRequest as _PlaceOrderRequest, Product as _Product, ProductId as _ProductId, Timestamp as _Timestamp, UpdateProductRequest as _UpdateProductRequest, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addProduct(arg0: AddProductRequest): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_AddProductRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_AddProductRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReview(arg0: AddReviewRequest): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addToCart(arg0: AddToCartRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async filterProducts(arg0: Category | null, arg1: string | null, arg2: bigint | null, arg3: bigint | null): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProducts(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProducts(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductReviews(arg0: ProductId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductReviews(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Wishlist> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactMessages();
            return result;
        }
    }
    async listProducts(arg0: Category | null): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return result;
        }
    }
    async placeOrder(arg0: PlaceOrderRequest): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactMessage(arg0: SubmitContactRequest): Promise<ContactMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0);
            return result;
        }
    }
    async toggleWishlist(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleWishlist(arg0);
            return result;
        }
    }
    async updateCartItem(arg0: UpdateCartItemRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItem(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: UpdateProductRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(to_candid_UpdateProductRequest_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(to_candid_UpdateProductRequest_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Category_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    deliveryAddress: _Address;
    couponCode: [] | [string];
    total: bigint;
    paymentMethod: _PaymentMethod;
    userId: _UserId;
    discountAmount: bigint;
    timestamp: _Timestamp;
    items: Array<_OrderItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: Address;
    couponCode?: string;
    total: bigint;
    paymentMethod: PaymentMethod;
    userId: UserId;
    discountAmount: bigint;
    timestamp: Timestamp;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n18(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        couponCode: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.couponCode)),
        total: value.total,
        paymentMethod: from_candid_PaymentMethod_n21(_uploadFile, _downloadFile, value.paymentMethod),
        userId: value.userId,
        discountAmount: value.discountAmount,
        timestamp: value.timestamp,
        items: value.items
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    name: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: _Category;
    brand: string;
    rating: bigint;
    price: bigint;
    reviewCount: bigint;
}): {
    id: ProductId;
    name: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: Category;
    brand: string;
    rating: bigint;
    price: bigint;
    reviewCount: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        stock: value.stock,
        imageUrl: value.imageUrl,
        category: from_candid_Category_n7(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        rating: value.rating,
        price: value.price,
        reviewCount: value.reviewCount
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Placed: null;
} | {
    Cancelled: null;
} | {
    Processing: null;
} | {
    Shipped: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Placed" in value ? OrderStatus.Placed : "Cancelled" in value ? OrderStatus.Cancelled : "Processing" in value ? OrderStatus.Processing : "Shipped" in value ? OrderStatus.Shipped : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    Card: null;
} | {
    NetBanking: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "Card" in value ? PaymentMethod.Card : "NetBanking" in value ? PaymentMethod.NetBanking : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Basketball: null;
} | {
    Tennis: null;
} | {
    Football: null;
} | {
    Cricket: null;
} | {
    Badminton: null;
}): Category {
    return "Basketball" in value ? Category.Basketball : "Tennis" in value ? Category.Tennis : "Football" in value ? Category.Football : "Cricket" in value ? Category.Cricket : "Badminton" in value ? Category.Badminton : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n16(_uploadFile, _downloadFile, x));
}
function to_candid_AddProductRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddProductRequest): _AddProductRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceOrderRequest_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderRequest): _PlaceOrderRequest {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProductRequest_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductRequest): _UpdateProductRequest {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: Category;
    brand: string;
    price: bigint;
}): {
    name: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: _Category;
    brand: string;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        stock: value.stock,
        imageUrl: value.imageUrl,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        price: value.price
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deliveryAddress: Address;
    couponCode?: string;
    paymentMethod: PaymentMethod;
    items: Array<OrderItem>;
}): {
    deliveryAddress: _Address;
    couponCode: [] | [string];
    paymentMethod: _PaymentMethod;
    items: Array<_OrderItem>;
} {
    return {
        deliveryAddress: value.deliveryAddress,
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        paymentMethod: to_candid_PaymentMethod_n30(_uploadFile, _downloadFile, value.paymentMethod),
        items: value.items
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    name: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: Category;
    brand: string;
    price: bigint;
}): {
    id: _ProductId;
    name: string;
    description: string;
    stock: bigint;
    imageUrl: string;
    category: _Category;
    brand: string;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        stock: value.stock,
        imageUrl: value.imageUrl,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        price: value.price
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    Card: null;
} | {
    NetBanking: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.Card ? {
        Card: null
    } : value == PaymentMethod.NetBanking ? {
        NetBanking: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivered: null;
} | {
    Placed: null;
} | {
    Cancelled: null;
} | {
    Processing: null;
} | {
    Shipped: null;
} {
    return value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Placed ? {
        Placed: null
    } : value == OrderStatus.Cancelled ? {
        Cancelled: null
    } : value == OrderStatus.Processing ? {
        Processing: null
    } : value == OrderStatus.Shipped ? {
        Shipped: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Basketball: null;
} | {
    Tennis: null;
} | {
    Football: null;
} | {
    Cricket: null;
} | {
    Badminton: null;
} {
    return value == Category.Basketball ? {
        Basketball: null
    } : value == Category.Tennis ? {
        Tennis: null
    } : value == Category.Football ? {
        Football: null
    } : value == Category.Cricket ? {
        Cricket: null
    } : value == Category.Badminton ? {
        Badminton: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
